name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install pytest
          pytest
